// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Web_Api.Context;

namespace Web_Api.Migrations
{
    [DbContext(typeof(MatchContext))]
    [Migration("20211026094625_Initial")]
    partial class Initial
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("ProductVersion", "5.0.11")
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("Data.Models.Match", b =>
                {
                    b.Property<int>("MatchId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("LoseId")
                        .HasColumnType("int");

                    b.Property<DateTime>("MatchDate")
                        .HasColumnType("datetime2");

                    b.Property<double>("Over1")
                        .HasColumnType("float");

                    b.Property<double>("Over2")
                        .HasColumnType("float");

                    b.Property<int>("Scores1")
                        .HasColumnType("int");

                    b.Property<int>("Scores2")
                        .HasColumnType("int");

                    b.Property<int>("Team1Id")
                        .HasColumnType("int");

                    b.Property<int>("Team2Id")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId")
                        .HasColumnType("int");

                    b.Property<int?>("TeamId1")
                        .HasColumnType("int");

                    b.Property<int>("WinId")
                        .HasColumnType("int");

                    b.HasKey("MatchId");

                    b.HasIndex("TeamId");

                    b.HasIndex("TeamId1");

                    b.ToTable("Matches");
                });

            modelBuilder.Entity("Data.Models.Team", b =>
                {
                    b.Property<int>("TeamId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<double>("TeamNRR")
                        .HasColumnType("float");

                    b.Property<string>("TeamName")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TeamId");

                    b.ToTable("Teams");
                });

            modelBuilder.Entity("Data.Models.Match", b =>
                {
                    b.HasOne("Data.Models.Team", null)
                        .WithMany("AwayScore")
                        .HasForeignKey("TeamId");

                    b.HasOne("Data.Models.Team", null)
                        .WithMany("HomeScore")
                        .HasForeignKey("TeamId1");
                });

            modelBuilder.Entity("Data.Models.Team", b =>
                {
                    b.Navigation("AwayScore");

                    b.Navigation("HomeScore");
                });
#pragma warning restore 612, 618
        }
    }
}
